### ISSUE TITLE
Permission errors

### ISSUE THREAD

**Issue by The-Compiler** [openhsr/connect#53]
Wenn es einen Ordner gibt ohne die richtigen Berechtigungen:

```
Downloading file Informatik/Fachbereich/Informationssicherheit_1_-_Grundlagen/InfSi1/Vorlesungsunterlagen/InfSi1-06-2.3.1-2-Cryptobasics-Encryption-SymmKey.pdf
Traceback (most recent call last):
  File "/usr/bin/openhsr-connect", line 11, in <module>
    load_entry_point('openhsr-connect==0.1.10', 'console_scripts', 'openhsr-connect')()
  File "/usr/lib/python3.6/site-packages/openhsr_connect/__main__.py", line 91, in main
    cli(standalone_mode=False)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/openhsr_connect/__main__.py", line 56, in sync_command
    smb_syncer.sync()
  File "/usr/lib/python3.6/site-packages/openhsr_connect/sync.py", line 212, in sync
    self.sync_tree(name, source, destination, '', excludes, cache)
  File "/usr/lib/python3.6/site-packages/openhsr_connect/sync.py", line 151, in sync_tree
    cache[remote_dir])
  File "/usr/lib/python3.6/site-packages/openhsr_connect/sync.py", line 151, in sync_tree
    cache[remote_dir])
  File "/usr/lib/python3.6/site-packages/openhsr_connect/sync.py", line 151, in sync_tree
    cache[remote_dir])
  File "/usr/lib/python3.6/site-packages/openhsr_connect/sync.py", line 134, in sync_tree
    remote_directories, remote_files = self.list_path(remote_path)
  File "/usr/lib/python3.6/site-packages/openhsr_connect/smb_sync.py", line 58, in list_path
    path_listing = self.connection.listPath(self.SMB_SHARE_NAME, path)
  File "/usr/lib/python3.6/site-packages/smb/SMBConnection.py", line 185, in listPath
    self._pollForNetBIOSPacket(timeout)
  File "/usr/lib/python3.6/site-packages/smb/SMBConnection.py", line 583, in _pollForNetBIOSPacket
    self.feedData(data)
  File "/usr/lib/python3.6/site-packages/nmb/base.py", line 54, in feedData
    self._processNMBSessionPacket(self.data_nmb)
  File "/usr/lib/python3.6/site-packages/nmb/base.py", line 75, in _processNMBSessionPacket
    self.onNMBSessionMessage(packet.flags, packet.data)
  File "/usr/lib/python3.6/site-packages/smb/base.py", line 137, in onNMBSessionMessage
    if self._updateState(self.smb_message):
  File "/usr/lib/python3.6/site-packages/smb/base.py", line 276, in _updateState_SMB2
    req.callback(message, **req.kwargs)
  File "/usr/lib/python3.6/site-packages/smb/base.py", line 577, in createCB
    errback(OperationFailure('Failed to list %s on %s: Unable to open directory' % ( path, service_name ), messages_history))
  File "/usr/lib/python3.6/site-packages/smb/SMBConnection.py", line 179, in eb
    raise failure
smb.smb_structs.OperationFailure: Failed to list Informatik\Fachbereich\Informationssicherheit_1_-_Grundlagen\InfSi1\Uebungen\Uebung-06-SymmetricKeySystems\Zusatzinfos-Analysefiles on skripte: Unable to open directory
```

**Comment by raphiz** [comment]
@The-Compiler was würdest du als Fix vorschlagen? Error loggen und weiter machen?

**Comment by The-Compiler** [comment]
Ja, wäre vermutlich am sinnvollsten.
